import { createRequire } from 'module';
import {
  IMAGE_DEVICE_SIZES,
  IMAGE_SIZES,
} from './src/lib/imageVariants/imageVariants.mjs';

const require = createRequire(import.meta.url);
const redirectsData = require('./src/data/redirects.json');

// Static export for GitHub Pages (CI: `npm run build:export`). Set here rather
// than injected by actions/configure-pages, because its injection also forces
// `images.unoptimized: true`, which disables the custom loader and srcset.
const isStaticExport = process.env.NEXT_OUTPUT_EXPORT === 'true';

/** @type {import('next').NextConfig} */
const nextConfig = {
  ...(isStaticExport && { output: 'export' }),
  reactStrictMode: true,
  productionBrowserSourceMaps: false,
  webpack: (config) => {
    config.module.rules.push({
      test: /\.svg$/i,
      use: ['@svgr/webpack'],
    });
    return config;
  },
  turbopack: {
    rules: {
      '*.svg': {
        loaders: ['@svgr/webpack'],
        as: '*.js',
      },
    },
  },
  images: {
    deviceSizes: IMAGE_DEVICE_SIZES,
    imageSizes: IMAGE_SIZES,
    // No image optimization server on a static host: srcset candidates point
    // to WebP variants generated by scripts/generate-image-variants.mjs.
    ...(isStaticExport && {
      loader: 'custom',
      loaderFile: './src/lib/imageVariants/exportImageLoader.ts',
    }),
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'i.imgur.com',
        port: '',
        pathname: '/*',
      },
    ],
  },
  async rewrites() {
    return [
      {
        source: '/:path*/',
        destination: '/:path*',
      },
    ];
  },
  async redirects() {
    // Host-based + wildcard rules are kept inline; only Node-hosted environments
    // honor these. On GitHub Pages static export, see scripts/generate-redirect-stubs.mjs
    // and app/not-found.tsx for the actual mechanism. The rest are sourced from
    // src/data/redirects.json (single source of truth).
    const fromJson = redirectsData.map((r) => ({
      source: r.source,
      destination: r.destination,
      permanent: true,
    }));
    return [
      {
        source: '/(.*)',
        destination: 'https://thebrightbyte.com/:path*',
        permanent: true,
        has: [
          {
            type: 'host',
            value: 'www.thebrightbyte.com',
          },
        ],
      },
      {
        source: '/blog/:slug',
        destination: '/insights/:slug',
        permanent: true,
      },
      ...fromJson,
    ];
  },
};

export default nextConfig;
