import { RevantaIconKey } from '@/src/data/revanta/types';
import {
  Award,
  BarChart3,
  Bot,
  Building2,
  CalendarDays,
  ClipboardList,
  Download,
  Dumbbell,
  FileText,
  Gift,
  History,
  Layers,
  LucideIcon,
  Mail,
  Map,
  Megaphone,
  MessageSquare,
  Network,
  Newspaper,
  Package,
  QrCode,
  ShieldCheck,
  Shirt,
  Smartphone,
  Tag,
  Target,
  Ticket,
  TrendingUp,
  Trophy,
  Truck,
  UserRound,
  Users,
  Wallet,
  Workflow,
  Zap,
} from 'lucide-react';

const ICONS: Record<RevantaIconKey, LucideIcon> = {
  award: Award,
  chart: BarChart3,
  bot: Bot,
  network: Network,
  ticket: Ticket,
  building: Building2,
  calendar: CalendarDays,
  users: Users,
  shield: ShieldCheck,
  mobile: Smartphone,
  trend: TrendingUp,
  dumbbell: Dumbbell,
  clipboard: ClipboardList,
  map: Map,
  trophy: Trophy,
  wallet: Wallet,
  file: FileText,
  message: MessageSquare,
  mail: Mail,
  gift: Gift,
  download: Download,
  qr: QrCode,
  newspaper: Newspaper,
  megaphone: Megaphone,
  shirt: Shirt,
  package: Package,
  truck: Truck,
  tag: Tag,
  user: UserRound,
  layers: Layers,
  history: History,
  zap: Zap,
  workflow: Workflow,
  target: Target,
};

export const RevantaIcon = ({
  name,
  className = 'h-[32px] w-[32px]',
}: {
  name: RevantaIconKey;
  className?: string;
}) => {
  const Icon = ICONS[name];
  return <Icon strokeWidth={1.8} className={className} aria-hidden='true' />;
};
